version: '2'
services:
  node:
    image: node:alpine
    restart: always 
    volumes:
      - ./src:/usr/src
      - /var/log/jsonee:/var/log/node
    working_dir: '/usr/src'
    command: npm start
    networks:
      - default
  nginx:
    image: nginx:alpine
    restart: always 
    volumes:
      - ./public:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - /var/log/jsonee:/var/log/nginx
    networks:
      - default
      - neco_link
networks:
  neco_link:
    external: true 

